theme: jekyll-theme-minimal
title: OptiCar - Circular optical perception
description: The demonstration platform of the OptiCar project
show_downloads: false
markdown: kramdown
exclude: ["ReadMe.md"]
baseurl: ""
logo: /assets/logo.jpg